#!name=高德地图合集
#!desc=去广告
#!author=RuCu6

[Rule]
# > 其它
URL-REGEX,^https:\/\/m5\.amap\.com\/ws\/shield\/scene\/recommend\?,REJECT-DICT

# > 导航详情页,路线规划,地点详情页,搜索详情页 - optimize1
URL-REGEX,^https:\/\/m5\.amap\.com\/ws\/(faas\/amap-navigation\/card-service-route-plan|shield\/(search\/new_hotword|search_poi\/tips_adv))\?,REJECT-DICT

# > 首页,推广卡片,红点角标,右上角动图,搜索框热词,左下角天气,消息横幅 - optimize2
URL-REGEX,^https:\/\/m5\.amap\.com\/ws\/(faas\/amap-navigation\/main-page-(assets|location)|mapapi\/hint_text\/offline_data|message\/notice\/list|shield\/search\/new_hotword|valueadded\/weather\/v2)\?,REJECT-DICT
URL-REGEX,^https:\/\/sns\.amap\.com\/ws\/msgbox\/pull_mp\?,REJECT-DICT

# > 我的页面,推广卡片 - optimize3

# > 附近页 - optimize4

# > 开屏广告 - optimize5

# > 打车页,红点角标,弹窗,推广卡片 - optimize6
URL-REGEX,^https:\/\/m5-zb\.amap\.com\/ws\/boss\/order(_web\/friendly_information|\/car\/king_toolbox_car_bubble)\?,REJECT-DICT

[Script]
optimize1 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amap.js,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/(search\/(common\/coupon\/info|poi\/detail)|search_poi\/(sug|mps|search\/sp|tips_operation_location))\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
optimize2 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amap.js,pattern=^https:\/\/m5\.amap\.com\/ws\/(faas\/amap-navigation\/main-page|shield\/frogserver\/aocs\/updatable\/1)\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
optimize3 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amap.js,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/dsp\/profile\/index\/nodefaasv3\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
optimize4 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amap.js,pattern=^https:\/\/m5\.amap\.com\/ws\/shield\/search\/nearbyrec_smart\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
optimize5 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amap.js,pattern=^https:\/\/m5\.amap\.com\/ws\/valueadded\/alimama\/splash_screen\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
optimize6 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amap.js,pattern=^https:\/\/m5-zb\.amap\.com\/ws\/(promotion-web\/resource(\/home)?|sharedtrip\/taxi\/order_detail_car_tips)\?,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% m5.amap.com,m5-zb.amap.com,sns.amap.com