#!name=代理分组
#!desc=代理分组

[Proxy Group]
#组-不测速
#AA = select,Edn,interval=600,timeout=5,select=0,url=http://www.gstatic.com/generate_204
#选择单个节点
#CC = select,韩国1,interval=600,timeout=5,select=0,url=http://www.gstatic.com/generate_204
IPTVHK = url-test,Ednovas - 香港#3,interval=600,tolerance=100,timeout=5,select=0,url=http://www.gstatic.com/generate_204
HDOHUB = url-test,Ednovas - 新加坡#2,interval=600,tolerance=100,timeout=5,select=0,url=http://www.gstatic.com/generate_204
EMBY = url-test,Ednovas - 新加坡#2,interval=600,tolerance=100,timeout=5,select=0,url=http://www.gstatic.com/generate_204
