#!name=常规去广告
#!desc=基础
#tencentVideo来源仓库：chengkongyiban，需先重装app，关掉模块，打开app登录账号后关掉app，再启用模块。

[Rule]
# >>>>>>>>>>>>>> ✅ 0 ✅ <<<<<<<<<<<<<<<
AND,((PROTOCOL,UDP),(DEST-PORT,443)),REJECT-NO-DROP

# > 12306
URL-REGEX,^https?:\/\/ad\.12306\.cn\/res\/adfiles(\/)?\/delivery\/,REJECT-IMG

# >>>>>>>>>>>>>> ✅ A ✅ <<<<<<<<<<<<<<<
# > amdc（gaoDeMap、caiNiao）
URL-REGEX,^http:\/\/amdc\.m\.taobao\.com\/amdc\/mobileDispatch,REJECT-DICT

# > aiQiYi
URL-REGEX,^https?:\/\/act\.vip\.iqiyi\.com\/interact\/api\/(v2\/show|show\.do),REJECT-200
URL-REGEX,^https?:\/\/iface\.iqiyi\.com\/api\/getNewAdInfo,REJECT-200
URL-REGEX,^https?:\/\/iface2\.iqiyi\.com\/fusion\/3\.0\/fusion_switch,REJECT-IMG

# >>>>>>>>>>>>>> ✅ C ✅ <<<<<<<<<<<<<<<
# > cheLaiLe
IP-CIDR,124.70.194.16/32,REJECT-DROP,no-resolve
URL-REGEX,^https?:\/\/logs\.chelaile\.net\.cn\/realtimelog,REJECT-DROP
URL-REGEX,^https?:\/\/(124\.71\.153\.172|.+\.chelaile.*\.cn)\/led-weather\/v\d+\/condition_brief\?,REJECT-200

# > caiNiao
URL-REGEX,^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.(adkeyword\.get|guoguo\.nbnetflow\.ads\.index|nbopen\.miniapp\.recommend\.cpc|nbmensa\.research\.researchservice\.(acquire|event|close))\.cn,REJECT-DICT
URL-REGEX,^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.longquan\.place\.getpageresourcecontent\.cn,REJECT-DICT
#aliPay 小程序
URL-REGEX,^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.adx\.flyad\.getad,REJECT-DICT

# >>>>>>>>>>>>>> ✅ K ✅ <<<<<<<<<<<<<<<
# > KFC
URL-REGEX,^https?:\/\/res\.kfc\.com\.cn\/CRM\/kfcad\/apphome(5|6)\/apphome,REJECT-200

# >>>>>>>>>>>>>> ✅ M ✅ <<<<<<<<<<<<<<<
# > maiDangLao
URL-REGEX,^https?:\/\/api\.mcd\.cn\/bff\/portal\/home\/splash,REJECT-200

# > maiDuiDui
URL-REGEX,^https?:\/\/api\.mddcloud\.com\.cn\/api\/(ad\/getClassAd|advert\/getHomepage)\.action,REJECT-IMG

# >>>>>>>>>>>>>> ✅ O ✅ <<<<<<<<<<<<<<<
# > other
URL-REGEX,^http:\/\/.+\.hzsanjiaomao\.com\/.+\.json,REJECT-DICT
DOMAIN-SUFFIX,umeng.com,REJECT-DROP
DOMAIN-SUFFIX,umengcloud.com,REJECT-DROP
DOMAIN,googleads.g.doubleclick-cn.net,REJECT-DROP
DOMAIN-SUFFIX,nx-perf.cn,REJECT-DROP
DOMAIN-SUFFIX,sigmob.cn,REJECT-DROP

# >>>>>>>>>>>>>> ✅ P ✅ <<<<<<<<<<<<<<<
# > pengPaiNews
DOMAIN,applog.thepaper.cn,REJECT-200
DOMAIN,applogs.thepaper.cn,REJECT-200
URL-REGEX,^https:\/\/app\.thepaper\.cn\/clt\/jsp\/v6\/lastReadRecommend,REJECT-DICT

# > panSearch
URL-REGEX,^https:\/\/www\.pansearch\.me\/api\/adsite,REJECT-DICT

# >>>>>>>>>>>>>> ✅ Q ✅ <<<<<<<<<<<<<<<
# > qianChengWuYou
URL-REGEX,^https?:\/\/appapi\.51job\.com\/api\/(\d+\/)?user\/stateboot\.php\?,REJECT-DICT

# > qq
DOMAIN-SUFFIX,bugly.qq.com,REJECT-DROP
DOMAIN-SUFFIX,trace.qq.com,REJECT-DROP
DOMAIN-SUFFIX,btrace.qq.com,REJECT-DROP

# >>>>>>>>>>>>>> ✅ T ✅ <<<<<<<<<<<<<<<
# > tencentVideo
AND,((PROTOCOL,HTTPS), (DOMAIN,iacc.qq.com)),REJECT-NO-DROP
URL-REGEX,^http:\/\/pgdt\.gtimg\.cn,REJECT-DICT
URL-REGEX,^http:\/\/.+\/vmind\.qqvideo\.tc\.qq\.com\/.+mp4,REJECT-DICT

# >>>>>>>>>>>>>> ✅ Y ✅ <<<<<<<<<<<<<<<
# > yangShiYingYin
URL-REGEX,^https?:\/\/api\.app\.cctv\.com\/api\/getVersion,REJECT-DICT

RULE-SET,https://raw.githubusercontent.com/fhqievg/rules/main/list/removeAdReject.list,REJECT

[Script]
xiaChuFang优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/xiaChuFang.js,pattern=^https?:\/\/(www|api)\.xiachufang\.com\/.+(account|ranking_list)?\/(detail_.+|detail|get_profile|paged_waterfall_recommendations|.*ranking_list.*|init_page)\.json,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
12306去AD = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/12306.js,pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
pengPaiNews优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/pengPaiNews.js,pattern=^https?:\/\/app\.thepaper\.cn\/clt\/(jsp\/v\d\/(loading|allNodes|channelContList|home_page_rcmd|newDetail|getTopBarData|categoryContList|new_detail_pph|sparkerNodeContList)|videoContList\/(channelList|nodeList)|course\/mine\/popularize),max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
amdc处理 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amdc.js,pattern=^http:\/\/.+\/amdc\/mobileDispatch,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
caiNiao优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/caiNiao.js,pattern=^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.(nbpresentation\.(homepage\.merge|pickup\.empty\.page|protocol\.homepage)\.get|guoguo\.nbnetflow\.ads\.(m?show|batch\.show\.v2))\.cn,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
caiNiao小程序 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/caiNiao.js,pattern=^https:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.mshow,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
555去AD = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/video/555.js,pattern=^https?:\/\/(run\.api\.qyfxgd\.cn|a\.weilai555\.com|a\.ecoliving168\.com)(:\d+)?\/api\/v1\/movie\/index_recommend,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
tencentVideo去AD = type=http-request,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/tx/removeVideoAd.js,pattern=^(https:\/\/i\.video|http:\/\/iacc)\.qq\.com\/$,max-size=0,timeout=10,script-update-interval=86400,enable=true
keEr去AD = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/keEr.js,pattern=^http:\/\/(kekeoo|ereroo)\.com\/(Aios\/config|banner)\.json,max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
keEr1 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/keEr.js,pattern=^http:\/\/api\.juliangcili\.com\/(\/)?api\/adver\/(data\/insert|space\/all\/list),max-size=0,requires-body=true,timeout=10,script-update-interval=86400,enable=true
aliDrive优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/vipUnlock/aliDrive.js,pattern=^https:\/\/api\.aliyundrive\.com\/apps\/v1\/users\/(apps|home)\/widgets$,requires-body=true,max-size=0,timeout=10,script-update-interval=86400,enable=true
cheLaiLe优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/cheLaiLe.js,pattern=^https?:\/\/(124\.71\.153\.172|.+\.chelaile.*\.cn)\/goocity\/(city\/(localCity|cityInfo|moreCities)|flowPos\/home)\?,requires-body=true,max-size=0,timeout=10,script-update-interval=86400,enable=true

[MITM]
hostname = %APPEND% *.chelaileapp.cn,*.chelaile.net.cn,124.71.153.172,www.xiachufang.com,api.xiachufang.com,appconf.mail.163.com,interface*.music.163.com,support.you.163.com,p.du.163.com,iadmusicmat.music.126.net,14.205.94.205,vip7.fzwdyy.cn:8083,intl.iqiyi.com,ssports.iqiyi.com,static.iqiyi.com,t7z.cupid.iqiyi.com,*.iqiyipic.com,act.vip.iqiyi.com,iface.iqiyi.com,iface2.iqiyi.com,pan.baidu.com,issuecdn.baidupcs.com,update.pan.baidu.com,staticsns.cdn.bcebos.com,ndstatic.cdn.bcebos.com,mob.mddcloud.com.cn,acs.m.taobao.com,api.izuiyou.com,res.kfc.com.cn,api.mcd.cn,ad.12306.cn,app.thepaper.cn,api.app.cctv.com,cn-acs.m.cainiao.com,guide-acs.m.taobao.com,run.api.qyfxgd.cn:*,a.weilai555.com:1000,a.ecoliving168.com,i.video.qq.com,iacc.qq.com,appapi.51job.com,blog.nilbt.com,www.pansearch.me,api.aliyundrive.com,www.xiaoxiongyouhao.com