#!name=常规去广告
#!desc=基础
#tencentVideo来源仓库：chengkongyiban，需先重装app，关掉模块，打开app登录账号后关掉app，再启用模块。

[Rule]
# > 其它
DOMAIN-SUFFIX,umeng.com,REJECT-DROP
DOMAIN-SUFFIX,umengcloud.com,REJECT-200
DOMAIN,googleads.g.doubleclick-cn.net,REJECT-DROP
DOMAIN-SUFFIX,nx-perf.cn,REJECT-DROP

# > pengPaiNews
DOMAIN,applog.thepaper.cn,REJECT-200
DOMAIN,applogs.thepaper.cn,REJECT-200

# > cheLaiLe
IP-CIDR,124.70.194.16/32,REJECT-DROP,no-resolve

# > tencentVideo
AND,((PROTOCOL,HTTPS), (DOMAIN,iacc.qq.com)),REJECT-NO-DROP

RULE-SET,https://raw.githubusercontent.com/fhqievg/rules/main/list/removeAdReject.list,REJECT

[URL Rewrite]
# >>>>>>>>>>>>>> ✅ 0 ✅ <<<<<<<<<<<<<<<
# > 12306
^https?:\/\/ad\.12306\.cn\/res\/adfiles(\/)?\/delivery\/ - REJECT-IMG

# >>>>>>>>>>>>>> ✅ A ✅ <<<<<<<<<<<<<<<
# > amdc（gaoDeMap、caiNiaoGuoGuo、taoPiaoPiao）
^http:\/\/amdc\.m\.taobao\.com\/amdc\/mobileDispatch$ - REJECT-DICT

# >>>>>>>>>>>>>> ✅ C ✅ <<<<<<<<<<<<<<<
# > cheLaiLe
^https?:\/\/logs\.chelaile\.net\.cn\/realtimelog - REJECT-DROP
^https?:\/\/(124\.71\.153\.172|.+\.chelaile.*\.(cn|com))\/led-weather\/v\d\/condition_brief\? - REJECT-200

# > caiNiaoGuoGuo
^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.(adkeyword\.get|guoguo\.nbnetflow\.ads\.index|nbmensa\.research\.researchservice\.(acquire|event|close))\.cn\/1\.0\? - REJECT-DICT

# >>>>>>>>>>>>>> ✅ I ✅ <<<<<<<<<<<<<<<
# > iqiyi
^https?:\/\/act\.vip\.iqiyi\.com\/interact\/api\/(v2\/show|show\.do) - REJECT-200
^https?:\/\/iface\.iqiyi\.com\/api\/getNewAdInfo - REJECT-200
^https?:\/\/iface2\.iqiyi\.com\/fusion\/3\.0\/fusion_switch - REJECT-IMG

# >>>>>>>>>>>>>> ✅ K ✅ <<<<<<<<<<<<<<<
# > KFC
^https?:\/\/res\.kfc\.com\.cn\/CRM\/kfcad\/apphome(5|6)\/apphome - REJECT-200

# >>>>>>>>>>>>>> ✅ M ✅ <<<<<<<<<<<<<<<
# > maiDangLao
^https?:\/\/api\.mcd\.cn\/bff\/portal\/home\/splash - REJECT-200

# > maiDuiDui
^https?:\/\/api\.mddcloud\.com\.cn\/api\/(ad\/getClassAd|advert\/getHomepage)\.action - REJECT-IMG

# >>>>>>>>>>>>>> ✅ O ✅ <<<<<<<<<<<<<<<
# > other
^http:\/\/.+\.hzsanjiaomao\.com\/.+\.json - REJECT-DICT

# >>>>>>>>>>>>>> ✅ P ✅ <<<<<<<<<<<<<<<
# > pengPaiNews
^https:\/\/app\.thepaper\.cn\/clt\/jsp\/v6\/lastReadRecommend - REJECT-DICT

# >>>>>>>>>>>>>> ✅ T ✅ <<<<<<<<<<<<<<<
# > tencentVideo
^http:\/\/pgdt\.gtimg\.cn - REJECT-DICT
^http:\/\/.+\/vmind\.qqvideo\.tc\.qq\.com\/.+mp4 - REJECT-DICT

# >>>>>>>>>>>>>> ✅ Y ✅ <<<<<<<<<<<<<<<
# > yangShiYingYin
^https?:\/\/api\.app\.cctv\.com\/api\/getVersion - REJECT-DICT

[Script]
xiaChuFang优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/xiaChuFang.js,pattern=^https?:\/\/(www|api)\.xiachufang\.com\/.+(account|ranking_list)?\/(detail_.+|detail|get_profile|paged_waterfall_recommendations|.*ranking_list.*|init_page)\.json,max-size=0,requires-body=true,timeout=10,script-update-interval=0,enable=true
12306去AD = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/12306.js,pattern=^https?:\/\/ad\.12306\.cn\/ad\/ser\/getAdList,max-size=0,requires-body=true,timeout=10,script-update-interval=0,enable=true
pengPaiNews优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/pengPaiNews.js,pattern=^https?:\/\/app\.thepaper\.cn\/clt\/(jsp\/v\d\/(loading|allNodes|channelContList|home_page_rcmd|newDetail|getTopBarData|categoryContList|new_detail_pph|sparkerNodeContList)|videoContList\/(channelList|nodeList)|course\/mine\/popularize),max-size=0,requires-body=true,timeout=10,script-update-interval=0,enable=true
amdc处理 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/amdc.js,pattern=^http:\/\/.+\/amdc\/mobileDispatch$,max-size=0,requires-body=true,timeout=10,script-update-interval=0,enable=true
caiNiaoGuoGuo优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/caiNiaoGuoGuo.js,pattern=^https:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.(guoguo\.nbnetflow\.ads\.m?show|nbpresentation\.(protocol\.homepage|homepage\.merge)\.get)\.cn\/1\.0\?,max-size=0,requires-body=true,timeout=10,script-update-interval=0,enable=true
555去AD = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/video/555.js,pattern=^https?:\/\/run\.api\.qyfxgd\.cn:\d+\/api\/v1\/movie\/index_recommend,max-size=0,requires-body=true,timeout=10,script-update-interval=0,enable=true
taoPiaoPiao优化 = type=http-response,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/taoPiaoPiao.js,pattern=^https?:\/\/acs\.m\.taobao\.com\/gw\/mtop\.film\.(life\.aristotle\.get|mtopintegrationapi\.homeconfig)\/1\.0\?,max-size=0,timeout=30,script-update-interval=0,enable=true
tencentVideo去AD = type=http-request,script-path=https://raw.githubusercontent.com/fhqievg/rules/main/script/tx/removeVideoAd.js,pattern=^(https:\/\/i\.video|http:\/\/iacc)\.qq\.com\/$,max-size=0,timeout=30,script-update-interval=0,enable=true

[MITM]
hostname = %APPEND% *.chelaileapp.cn,*.chelaile.net.cn,124.71.153.172,www.xiachufang.com,api.xiachufang.com,appconf.mail.163.com,interface*.music.163.com,support.you.163.com,p.du.163.com,iadmusicmat.music.126.net,14.205.94.205,vip7.fzwdyy.cn:*,intl.iqiyi.com,ssports.iqiyi.com,static.iqiyi.com,t7z.cupid.iqiyi.com,*.iqiyipic.com,act.vip.iqiyi.com,iface.iqiyi.com,iface2.iqiyi.com,pan.baidu.com,issuecdn.baidupcs.com,update.pan.baidu.com,staticsns.cdn.bcebos.com,ndstatic.cdn.bcebos.com,mob.mddcloud.com.cn,acs.m.taobao.com,api.izuiyou.com,res.kfc.com.cn,api.mcd.cn,ad.12306.cn,app.thepaper.cn,api.app.cctv.com,cn-acs.m.cainiao.com,run.api.qyfxgd.cn:*,i.video.qq.com,iacc.qq.com
